---
title: "Processing and preliminary clustering"
subtitle: "CSF_01 - patient:4608"
author:
- name: Paula Nieto
  affiliation: 
  - Centro Nacional de Análisis Genómico (CNAG)
  email: paula.nieto@cnag.crg.eu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  results = "hide",
  warning = FALSE,
  message = FALSE,
  tidy = TRUE
)
```

```{r surce-utils, include=FALSE}
tryCatch({
  source("/scratch/devel/pnieto/scripts/r_utils/utils.R")
}, error = function(e) {
  source("S:/scripts/r_utils/utils.R")
})
library(dittoSeq)
```

```{r set-params}
root <- get_root_dir()
proj_name <- "CSF_01" 
library <- "4608" 
patient <- "P01"
sample <- "S01"
proj_dir <- glue("{root}/CSF/data/{proj_name}")
data_dir <- glue("{proj_dir}/output/01_QC_filtering")
out_dir <- glue("{proj_dir}/output/02_processing_clustering")
```

```{r create-output-folder}
# create output folder if it doesn't exist yet
if (!file.exists(out_dir)) {
  dir.create(out_dir)
}
```

```{r load annotated object}
data <- readRDS(glue("{out_dir}/{proj_name}_{library}_annotated.rds"))
```

```{r define color palette}
pal <- as.vector(pals::polychrome())[1:length(unique(data$annot))]
names(pal) <- unique(data$annot)
```

## Clustering

```{r normalize and cluster, eval = FALSE}
data <- readRDS(glue("{data_dir}/{proj_name}_{library}_filtered.rds"))
data <- subset(data, subset = keep_cells == TRUE)

unique(data$project)
unique(data$sample)

data <- data %>%
  NormalizeData() %>% 
  FindVariableFeatures(nfeatures = 3000) %>%
  ScaleData() %>%
  RunPCA() %>%
  RunUMAP(dims = 1:20) %>%
  FindNeighbors(dims = 1:20) %>%
  FindClusters(resolution = seq(from = 0.1, to = 1, by = 0.1))
```

```{r all resolutions, fig.height=10, fig.width=10}
DimPlot(data, group.by = paste0("RNA_snn_res.", seq(from = 0.1, to = 1, by = 0.1)), label = TRUE) & NoLegend()
```

```{r set resolution}
# set selected resolution
res <- "0.1"
```

```{r fix clusters, eval = FALSE}
Idents(data) <- paste0("RNA_snn_res.", res)
# data <- CellSelector(plot = DimPlot(data), object = data, ident = 1)
data$seurat_clusters <- as.factor(as.character(Idents(data)))
data@meta.data[,paste0("RNA_snn_res.", res)] <- as.factor(as.character(Idents(data)))
Idents(data) <- as.factor(as.character(Idents(data)))
```

We will select resolution `r res`

```{r plot selected resolution}
# UMAP with selected resolution
DimPlot(data, group.by = paste0("RNA_snn_res.", res), pt.size = 2, label = TRUE) & NoLegend()
```

```{r eval=FALSE}
data$seurat_clusters <- data@meta.data[,paste0("RNA_snn_res.", res)]
Idents(data) <- paste0("RNA_snn_res.", res)
DefaultAssay(data) <- 'RNA'
```

Recheck quality of clusters

```{r}
Idents(data) <- "seurat_clusters"
FeaturePlot(
  data,
  features = c("nCount_RNA", "nFeature_RNA", "percent.mt", "doublet_score"),
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE,
  label.size = 3,
  ncol = 2,
  pt.size = 0.8
  )
```

CD45 expression (immune cells)

```{r fig.width=9}
Idents(data) <- paste0("RNA_snn_res.", res)
FeaturePlot(
  data,
  pt.size = 1,
  features = "PTPRC",
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE
  )
```

***

## Known marker genes

```{r}
marker_genes <- c(
  "S100A8", "CD14", # mono
  "C1QC", "CD68", # macro
  "CD4", "CD8B", "CD3E", # T cells
  "COL1A1", # CAFs
  "CD1C", # cDC
  "MKI67", # prolif
  "KLRB1", # NK
  "MS4A1", "CD79B", # B cells
  "LILRA4", # pDC
  "MLANA" # tumor cells/melanocytes
)
```

```{r fig.width=10, fig.height=12}
Idents(data) <- paste0("RNA_snn_res.", res)
FeaturePlot(
  data,
  features = marker_genes,
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE,
  label.size = 2,
  ncol = 3,
  pt.size = 1
  )
```

```{r fig.width=10}
FeaturePlot(
  data,
  features = c("BCL2", "BCL6", "CD10"),
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE,
  label.size = 2,
  pt.size = 1
  )
```

## Preliminary annotation

```{r find cluster markers, eval = FALSE}
markers <- FindAllMarkers(
  object = data,
  only.pos = TRUE
)

# save file
saveRDS(markers, glue("{out_dir}/{proj_name}_{library}_general_cluster_markers_res{res}.rds"))
# write to excel file
openxlsx::write.xlsx(split(markers, markers$cluster), 
                     file = glue("{out_dir}/{proj_name}_{library}_general_cluster_markers_res{res}.xlsx"),
                     overwrite = TRUE)
```

```{r eval = FALSE}
Idents(data) <- "seurat_clusters"
new.cluster.ids <- c("Tumor cells", "bad quality", "Melanocytes", "Tumor cells", "Tumor cells", "Myeloid", "Tumor cells", "bad quality", "Myeloid", "T cells", "Proliferative", "bad quality", "Fibroblasts", "Endothelial", "T cells", "Myeloid", "Myeloid", "Endothelial")
names(new.cluster.ids) <- c(0:17)
data <- RenameIdents(data, new.cluster.ids)
data$annot <- Idents(data)
data <- subset(data, annot %in% c("doublets", "bad quality", "RBC"), invert = TRUE)
data$annot <- as.character(data$annot)
# save annotated object
saveRDS(data, glue("{out_dir}/{proj_name}_{library}_annotated.rds"))
```

```{r}
DimPlot(data, group.by = 'annot', pt.size = 1, label = TRUE, cols = pal) +
  NoLegend() +
  labs(
    title = "General Annotation",
    caption = paste(unique(data$sample),unique(data$project))
    )
```

```{r fig.width=10, fig.height=8}
p1 <- dittoSeq::dittoBarPlot(
  data,
  var = "annot",
  group.by = "sample",
  color.panel = pal,
  retain.factor.levels = T
) +
  ggtitle("") +
  theme(text = element_text(size = 18)) +
  NoLegend()
p2 <- dittoSeq::dittoBarPlot(
  data,
  var = "annot",
  group.by = "annot",
  color.panel = pal,
  retain.factor.levels = T,
  scale = "count"
) +
  ggtitle("") +
  theme(text = element_text(size = 18))
p1+p2
```

## Top markers

```{r}
# Marker heatmap
Idents(data) <- "annot"
markers <- FindAllMarkers(data, only.pos = TRUE, max.cells.per.ident = 500)
markers <- filter(markers, p_val_adj < 0.01)
markers$cluster <- as.character(markers$cluster)
markers$cluster <- factor(markers$cluster, levels = names(pal))

top_markers <- markers %>%
  arrange(cluster) %>% 
  group_by(cluster) %>%
  top_n(n = 5, wt = avg_log2FC) %>% 
  arrange(cluster) %>% 
  pull(gene)

top_genes_avg <- AverageExpression(
  object = data,
  features = top_markers,
  return.seurat = TRUE, 
  group.by = 'annot',
  assays = "RNA", 
  slot = "data"
  )
top_genes_avg$Annotation <- rownames(top_genes_avg@meta.data)
top_genes_avg$Annotation <- factor(top_genes_avg$Annotation, levels = names(pal))
```

```{r results='markup', fig.height=9}
dittoSeq::dittoHeatmap(
  object = top_genes_avg,
  genes = top_markers,
  annot.by = "Annotation",
  order.by = "Annotation",
  annot.colors = pal,
  scaled.to.max = TRUE,
  cluster_cols = FALSE,
  cluster_rows = FALSE,
  heatmap.colors.max.scaled = viridisLite::magma(50, alpha = 1, begin = 0, end = 1, direction = 1),
  complex = TRUE
)
```

## Cell composition

```{r results='markup'}
t1 <- table(data$annot) %>% as.data.frame()
colnames(t1) <- c("Annotation", "# Cells")

t2 <- round((table(data$annot)/dim(data)[2])*100,2) %>% as.data.frame()
colnames(t2) <- c("Annotation", "% Cells")

merge(t1, t2) %>% 
  DT::datatable(rownames = NULL, caption = paste(unique(data$sample),unique(data$project)))
```

# High-res annotation

```{r eval = FALSE}
res <- "1"
data$patient <- patient
data$library <- data$sample
data$sample <- sample
data$annot_2 <- paste(data$annot, data$RNA_snn_res.1)
```

```{r eval = FALSE}
# increase B cell resolution
Idents(data) <- "RNA_snn_res.0.3"
data <- FindSubCluster(data, cluster = 2, graph.name = "RNA_snn", resolution = 1)

data$annot_2[data$annot == "B cells"] <- paste("B cells", data$sub.cluster[data$annot == "B cells"])
```

```{r plot high resolution}
# UMAP with selected resolution
DimPlot(data, group.by = "annot_2", pt.size = 1.5, cols = as.vector(pals::polychrome()))
```

```{r eval = FALSE}
# check
table(data$annot_2) %>% as.data.frame() %>% arrange(Freq)
# remove T cells 11 -> two misclassified cells
data <- subset(data, annot_2 == "T cells 11", invert = TRUE)

data$Index <- str_replace(rownames(data@meta.data), pattern = "CSF_01_4608_", replacement = "")
data@meta.data[,c("Index", "annot_2")] %>% 
  write_delim(., file = glue("{proj_dir}/output/05_SComatic/{library}/barcode_annotations.tsv"), delim = "\t", col_names = TRUE)
```

```{r eval = FALSE}
Idents(data) <- "annot_2"
markers <- FindAllMarkers(
  object = data,
  only.pos = TRUE
)

# save file
saveRDS(markers, glue("{out_dir}/{proj_name}_{library}_general_cluster_markers_res{res}.rds"))
# write to excel file
openxlsx::write.xlsx(split(markers, markers$cluster), 
                     file = glue("{out_dir}/{proj_name}_{library}_general_cluster_markers_res{res}.xlsx"),
                     overwrite = TRUE)
```

```{r eval = FALSE}
# save annotated object
saveRDS(data, glue("{out_dir}/{proj_name}_{library}_annotated.rds"))
```

## Cancer Hallmarks

### Ribosomal content

```{r eval = FALSE}
data[["percent.rb"]] <- PercentageFeatureSet(data, pattern = "^RB|^RP")
```

```{r}
FeaturePlot(
  data,
  features = c("percent.rb"),
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE,
  label.size = 2,
  pt.size = 1
  )
```

```{r}
VlnPlot(
  data,
  features = "percent.rb",
  group.by = "annot_2",
  cols = as.vector(pals::polychrome())
) +
  NoLegend()
```

### Oxidative Phosphorilation

```{r}
oxphos_sig <- c("ABCB7", "ACAA1", "ACAA2", "ACADM", "ACADSB", "ACADVL", "ACAT1", "ACO2", "AFG3L2", "AIFM1", "ALAS1", "ALDH6A1", "ATP1B1", "ATP5F1A", "ATP5F1B", "ATP5F1C", "ATP5F1D", "ATP5F1E", "ATP5PB", "ATP5MC1", "ATP5MC2", "ATP5MC3", "ATP5PD", "ATP5ME", "ATP5PF", "ATP5MF", "ATP5MG", "ATP5PO", "ATP6AP1", "ATP6V0B", "ATP6V0C", "ATP6V0E1", "ATP6V1C1", "ATP6V1D", "ATP6V1E1", "ATP6V1F", "ATP6V1G1", "ATP6V1H", "BAX", "BCKDHA", "BDH2", "MPC1", "CASP7", "COX10", "COX11", "COX15", "COX17", "COX4I1", "COX5A", "COX5B", "COX6A1", "COX6B1", "COX6C", "COX7A2", "COX7A2L", "COX7B", "COX7C", "COX8A", "CPT1A", "CS", "CYB5A", "CYB5R3", "CYC1", "CYCS", "DECR1", "DLAT", "DLD", "DLST", "ECH1", "ECHS1", "ECI1", "ETFA", "ETFB", "ETFDH", "FDX1", "FH", "FXN", "GLUD1", "GOT2", "GPI", "GPX4", "GRPEL1", "HADHA", "HADHB", "HCCS", "HSD17B10", "HSPA9", "HTRA2", "IDH1", "IDH2", "IDH3A", "IDH3B", "IDH3G", "IMMT", "ISCA1", "ISCU", "LDHA", "LDHB", "LRPPRC", "MAOB", "MDH1", "MDH2", "MFN2", "MGST3", "MRPL11", "MRPL15", "MRPL34", "MRPL35", "MRPS11", "MRPS12", "MRPS15", "MRPS22", "MRPS30", "MTRF1", "MTRR", "MTX2", "NDUFA1", "NDUFA2", "NDUFA3", "NDUFA4", "NDUFA5", "NDUFA6", "NDUFA7", "NDUFA8", "NDUFA9", "NDUFAB1", "NDUFB1", "NDUFB2", "NDUFB3", "NDUFB4", "NDUFB5", "NDUFB6", "NDUFB7", "NDUFB8", "NDUFC1", "NDUFC2", "NDUFS1", "NDUFS2", "NDUFS3", "NDUFS4", "NDUFS6", "NDUFS7", "NDUFS8", "NDUFV1", "NDUFV2", "NNT", "NQO2", "OAT", "OGDH", "OPA1", "OXA1L", "PDHA1", "PDHB", "PDHX", "PDK4", "PDP1", "PHB2", "PHYH", "PMPCA", "POLR2F", "POR", "PRDX3", "RETSAT", "RHOT1", "RHOT2", "SDHA", "SDHB", "SDHC", "SDHD", "SLC25A11", "SLC25A12", "SLC25A20", "SLC25A3", "SLC25A4", "SLC25A5", "SLC25A6", "SUCLA2", "SUCLG1", "SUPV3L1", "SURF1", "TCIRG1", "TIMM10", "TIMM13", "TIMM17A", "TIMM50", "TIMM8B", "TIMM9", "TOMM22", "TOMM70", "UQCR10", "UQCR11", "UQCRB", "UQCRC1", "UQCRC2", "UQCRFS1", "UQCRH", "UQCRQ", "VDAC1", "VDAC2", "VDAC3")

data <- UCell::AddModuleScore_UCell(data, features = list(OXPHOS = oxphos_sig))
```

```{r}
FeaturePlot(
  data,
  features = "OXPHOS_UCell",
  cols = c("#ADD8E633", "#E46726"),
  order = TRUE,
  label = TRUE,
  label.size = 2,
  pt.size = 1
  )
```

```{r}
VlnPlot(
  data,
  features = "OXPHOS_UCell",
  group.by = "annot_2",
  cols = as.vector(pals::polychrome())
) +
  NoLegend()
```

```{r eval = FALSE}
# save annotated object
saveRDS(data, glue("{out_dir}/{proj_name}_{library}_annotated.rds"))
```

## TCR/BCR

Explore the TCR and BCR repertoires captured (if available).

```{r tcr-exist}
doNextChunk <- ("cloneType" %in% colnames(data@meta.data))
```

```{r eval = !doNextChunk, results='markup'}
"No TCR sequenced for this library!"
```

```{r eval = FALSE}
# TCR
tcr <- read.csv(glue("{proj_dir}/jobs/{library}/{library}/outs/per_sample_outs/{library}/vdj_t/filtered_contig_annotations.csv"))

combined_tcr <- combineTCR(tcr, 
                ID = library, 
                samples = proj_name, 
                cells ="T-AB")

# rename to match sc
combined_tcr[[glue("{proj_name}_{library}")]]$barcode <- str_remove_all(combined_tcr[[glue("{proj_name}_{library}")]]$barcode, pattern = "-1$|-2$|-3$")

# BCR
bcr <- read.csv(glue("{proj_dir}/jobs/{library}/{library}/outs/per_sample_outs/{library}/vdj_b/filtered_contig_annotations.csv"))

combined_bcr <- combineBCR(bcr,
                ID = library,
                samples = proj_name, 
                threshold = 0.5
                )

# rename to match sc
combined_bcr[[glue("{proj_name}_{library}")]]$barcode <- str_remove_all(combined_bcr[[glue("{proj_name}_{library}")]]$barcode, pattern = "-1$|-2$|-3$")

list.receptors <- c(combined_tcr, combined_bcr)

data <- combineExpression(
  list.receptors, 
  data, 
  cloneCall="aa", 
  proportion = FALSE, 
  cloneTypes=c(Single=1, Small=5, Medium=20, Large=50, Hyperexpanded=100))

# save annotated object with TCR data
saveRDS(data, glue("{out_dir}/{proj_name}_{library}_annotated.rds"))
```

```{r eval = doNextChunk, results='markup'}
data@meta.data[, c("sample", "Frequency", "cloneType", "CTaa", "annot")] %>% 
  filter(annot %in% c("T cells", "B cells")) %>% 
  unique() %>% 
  filter(!is.na(cloneType)) %>% 
  arrange(desc(Frequency)) %>% 
  DT::datatable(rownames = FALSE)
```

```{r fig.width=9, eval = doNextChunk}
colorblind_vector <- colorRampPalette(rev(c("#0D0887FF", "#47039FFF", 
              "#7301A8FF", "#9C179EFF", "#BD3786FF", "#D8576BFF",
              "#ED7953FF","#FA9E3BFF", "#FDC926FF", "#F0F921FF")))

slot(data, "meta.data")$cloneType <- factor(slot(data, "meta.data")$cloneType, 
                levels = c("Hyperexpanded (50 < X <= 100)", 
                           "Large (20 < X <= 50)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)", NA))

colorblind_vector <- colorblind_vector(5)
names(colorblind_vector) <- c("Hyperexpanded (50 < X <= 100)", 
                           "Large (20 < X <= 50)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)")
```

```{r fig.width=9, eval = doNextChunk}
DimPlot(data, group.by = "cloneType", pt.size = 1) +
    scale_color_manual(values = colorblind_vector, na.value="grey") + 
  theme(plot.title = element_blank(),
        text = element_text(size = 18))
```

```{r fig.width=9, eval = doNextChunk}
"Number of clones (not cells!) per type and sample"
df <- data@meta.data[, c("sample", "cloneType", "CTaa", "annot")] %>% 
  filter(!is.na(CTaa)) %>% 
  filter(annot %in% c("T cells", "B cells"))
rownames(df) <- NULL
df <- unique(df)
table(df[, c("sample", "cloneType", "annot")]) %>% 
  as.data.frame() %>% 
  ggplot(aes(x=sample, y=Freq, fill=cloneType)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_text(aes(label=Freq), vjust=-0.5, color="black",
            position = position_dodge(0.9), size=3.5) +
  facet_grid(.~annot) +
  scale_fill_manual(values = colorblind_vector) +
  theme_classic() +
  theme(plot.title = element_blank(),
        text = element_text(size = 18))
```

```{r results='markup', eval = doNextChunk}
"Percentage of T cells that have a TCR (TRUE) and don't have one (FALSE)."

t1 <- table(!is.na(subset(data, annot == "T cells")$cloneType)) %>% as.data.frame()
colnames(t1) <- c("TCRs", "# Cells")

t2 <- round((table(!is.na(subset(data, annot == "T cells")$cloneType))/dim(subset(data, annot == "T cells"))[2])*100,2) %>% as.data.frame()
colnames(t2) <- c("TCRs", "% Cells")

merge(t1, t2) %>% 
  DT::datatable(rownames = NULL, caption = paste(unique(data$sample),unique(data$project)))
```

```{r results='markup', eval = FALSE}
"Percentage of B cells that have a BCR (TRUE) and don't have one (FALSE)."

t1 <- table(!is.na(subset(data, annot == "B cells")$cloneType)) %>% as.data.frame()
colnames(t1) <- c("BCRs", "# Cells")

t2 <- round((table(!is.na(subset(data, annot == "B cells")$cloneType))/dim(subset(data, annot == "B cells"))[2])*100,2) %>% as.data.frame()
colnames(t2) <- c("BCRs", "% Cells")

merge(t1, t2) %>% 
  DT::datatable(rownames = NULL, caption = paste(unique(data$sample),unique(data$project)))
```

<a href="#top">Back to top</a>

***
