---
title: "Automatic_annotation"
author: 
- name: Paula Nieto
  affiliation: 
  - Centro Nacional de Análisis Genómico (CNAG)
  email: paula.nieto@cnag.crg.eu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    self_contained: yes
    mode: selfcontained
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CSF_01

* [P01 - 4608](CSF_01_4608_Automatic_HR_Annotation.html)
* [P02 - 4839](CSF_01_4839_Automatic_HR_Annotation.html)
* [P03 - 5929](CSF_01_5929_Automatic_HR_Annotation.html)
* [P04 - 5700](CSF_01_5700_Automatic_HR_Annotation.html)
* [P05 - 5792](CSF_01_5792_Automatic_HR_Annotation.html)

# CSF_02

* [P06 - 7921](CSF_02_7921_Automatic_HR_Annotation.html)
* [P07 - 7974](CSF_02_7974_Automatic_HR_Annotation.html)

# CSF_03

* [P08 - 3087](CSF_03_3087_Automatic_HR_Annotation.html)
* [P09 - 3887](CSF_03_3887_Automatic_HR_Annotation.html)
* [P10 - 8102](CSF_03_8102_Automatic_HR_Annotation.html)
* [P11 - 3054](CSF_03_3054_Automatic_HR_Annotation.html)

# CSF_04

* [P12 - 5959](CSF_04_5959_Automatic_HR_Annotation.html)
* [P13 - 4776](CSF_04_4776_Automatic_HR_Annotation.html)
* [P14 - 4535](CSF_04_4535_Automatic_HR_Annotation.html)

# CSF_05

* [P10 - 8084](CSF_05_8084_Automatic_HR_Annotation.html)
* [P15 - 4759](CSF_05_4759_Automatic_HR_Annotation.html)
* [P16 - 4723](CSF_05_4723_Automatic_HR_Annotation.html)

# CSF_06

* [P12 - 8022](CSF_06_8022_Automatic_HR_Annotation.html)
* [P16 - 4619](CSF_06_4619_Automatic_HR_Annotation.html)
* [P07 - 8194](CSF_06_8194_Automatic_HR_Annotation.html)
* [P12 - 3885](CSF_06_3885_Automatic_HR_Annotation.html)
* [P12 - 8202](CSF_06_8202_Automatic_HR_Annotation.html)
