---
title: "Glioblastoma patients integration"
subtitle: "P02 & P05"
author:
- name: Paula Nieto
  affiliation: 
  - Centro Nacional de Análisis Genómico (CNAG)
  email: paula.nieto@cnag.eu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  results = "hide",
  warning = FALSE,
  message = FALSE,
  tidy = TRUE
)
```

```{r set-params}
library(tidyverse)
library(glue)
library(magrittr)
library(Seurat)
library(glue)
library(harmony)
library(scRepertoire)
library(dittoSeq)

# set path depending if on cluster or local
root_dir <- ifelse(
  grepl(dirname(getwd()), pattern = "/scratch/"),
  "/scratch/devel/pnieto", #true statement
  "S:" # false statement
)

# name of the project directory
proj_dir <- glue::glue("{root_dir}/projects/CSF")
# name of output folder
out_dir <- glue("{proj_dir}/output/integration/Glioblastoma") %T>%
  dir.create()
```

```{r}
# load annotated object
data <- readRDS(glue("{out_dir}/all_cells_signature_type.rds"))
```

```{r}
print(table(data$patient))
```

# Integration

```{r eval = FALSE}
# get patients to integrate
sample_list <- c("4839", "5792")
# files <- list.files(glue("{proj_dir}/data"), recursive = "TRUE", pattern = "HR_automatic_annotated_CT.rds", full.names = TRUE) %>% 
  # grep(pattern = paste(sample_list, collapse = "|"), value = TRUE)
files <- c(glue("{proj_dir}/data/CSF_01/output/05_CellTypist/4839_HR_automatic_annotated_CT.rds"), 
           glue("{proj_dir}/data/CSF_01/output/05_CellTypist/5792_HR_automatic_annotated_CT.rds"))
data <- purrr::map(files, readRDS)
```

```{r eval = FALSE}
data <- merge(data[[1]], data[[2]])

data <- data %>%
  NormalizeData() %>% 
  FindVariableFeatures(nfeatures = 3000) %>%
  ScaleData() %>%
  RunPCA()

# defined the group_by_vars variable as a factor
data@meta.data$sample <- as.factor(data@meta.data$sample)
data <- RunHarmony(data, group.by.vars = c("patient"))

data <- data %>%
  RunUMAP(reduction = "harmony", dims = 1:25) %>%
  FindNeighbors(reduction = "harmony", dims = 1:25) %>%
  FindClusters(resolution = seq(0.1, 1, 0.1))

data$annot <- recode(data$annot,
                     "T cells - NK" = "T cells",
                     "DC1" = "DC", 
                     "Tumor" = "Other cells",
                     "Prolif" = "Proliferative",
                     "Myeloid" = "Myeloid cells",
                     "Macrophages" = "Myeloid cells",
                     "Monocytes and macrophages" = "Myeloid cells",
                     "Monocytes" = "Myeloid cells"
                     )

# save clustered dataset
saveRDS(data, glue("{out_dir}/all_cells_integrated.rds"))
```

Check if integration worked well

```{r}
DimPlot(data, 
        group.by = "patient",
        shuffle = TRUE,
        pt.size = 1
      ) + 
  theme(text = element_text(size = 20))
```

```{r fig.width=10}
DimPlot(
  data, 
  group.by = "annot", 
  split.by = "patient",
  cols = as.vector(pals::polychrome())
  ) +
  labs(
    title = "General annotation"
  ) +
  theme(text = element_text(size = 20))
```

```{r}
dittoBarPlot(
  data,
  var = "annot",
  group.by = "patient",
  color.panel = as.vector(pals::polychrome())
) +
  NoLegend() +
  ggtitle("") +
  dittoBarPlot(
  data,
  var = "annot",
  group.by = "patient", 
  scale = "count",
  color.panel = as.vector(pals::polychrome())
) +
  ggtitle("") &
  theme(text = element_text(size = 20))
```

```{r fig.width=10}
DimPlot(
  data, 
  group.by = "auto_annot", 
  split.by = "patient",
  cols = as.vector(pals::glasbey())
  ) +
  labs(
    title = "Automatic annotation"
  ) +
  theme(text = element_text(size = 20))
```

```{r}
dittoBarPlot(
  data,
  var = "auto_annot",
  group.by = "patient",
  color.panel = as.vector(pals::glasbey())
) +
  NoLegend() +
  ggtitle("") +
  dittoBarPlot(
  data,
  var = "auto_annot",
  group.by = "patient", 
  scale = "count",
  color.panel = as.vector(pals::glasbey())
) +
  ggtitle("") &
  theme(text = element_text(size = 20))
```

```{r fig.width=15}
t <- table(data$CT_predicted_labels) %>% 
  as.data.frame() %>% 
  filter(Freq >= 5) %>% 
  pull(Var1)

DimPlot(
  subset(data, CT_predicted_labels %in% t), 
  group.by = "CT_predicted_labels", 
  split.by = "patient",
  cols = c(as.vector(pals::alphabet()), as.vector(pals::alphabet2()))
  ) +
  labs(
    title = "CellTypist annotation"
  ) +
  theme(text = element_text(size = 20), legend.text = element_text(size = 10))
```

```{r fig.width=20}
dittoBarPlot(
  subset(data, CT_predicted_labels %in% t), 
  var = "CT_predicted_labels",
  group.by = "patient",
  color.panel = c(as.vector(pals::alphabet()), as.vector(pals::alphabet2()))
) +
  NoLegend() +
  ggtitle("") +
  dittoBarPlot(
  subset(data, CT_predicted_labels %in% t), 
  var = "CT_predicted_labels",
  group.by = "patient", 
  scale = "count",
  color.panel = c(as.vector(pals::alphabet()), as.vector(pals::alphabet2()))
) +
  ggtitle("") &
  theme(text = element_text(size = 20))
```

```{r fig.width=10, fig.height=10, eval = FALSE}
data <- readRDS(glue("{out_path}/all_cells_integrated.rds"))
DimPlot(data, 
        group.by = grep(colnames(data@meta.data), pattern = "RNA_snn_res", value = TRUE),
        label = TRUE,
        pt.size = 1,
        label.size = 3
        )

data$seurat_clusters <- data$RNA_snn_res.1
Idents(data) <- "RNA_snn_res.1"

data$seurat_clusters <- as.factor(as.character(Idents(data)))
data$RNA_snn_res.1 <- as.factor(as.character(Idents(data)))
Idents(data) <- as.factor(as.character(Idents(data)))

markers <- FindAllMarkers(
  object = data,
  only.pos = TRUE
)

# save file
saveRDS(markers, glue("{out_dir}/Glioblastoma_all_cell_cluster_markers.rds"))
# write to excel file
openxlsx::write.xlsx(split(markers, markers$cluster), 
                     file = glue("{out_dir}/Glioblastoma_all_cell_cluster_markers.xlsx"),
                     overwrite = TRUE)
```

```{r}
DimPlot(data, 
        group.by = "seurat_clusters",
        label = TRUE,
        pt.size = 1.5,
        label.size = 6,
        cols = as.vector(pals::trubetskoy())
      ) + 
  NoLegend() +
  theme(text = element_text(size = 20))
```

```{r fig.width=10}
DimPlot(data, 
        group.by = "seurat_clusters",
        split.by = "patient",
        label = TRUE,
        pt.size = 1.5,
        label.size = 4,
        ncol = 4,
        cols = as.vector(pals::trubetskoy())
        ) + 
  NoLegend() +
  theme(text = element_text(size = 20)) 
```

```{r}
dittoBarPlot(
  data,
  var = "seurat_clusters",
  group.by = "patient",
  color.panel = as.vector(pals::trubetskoy())
) +
  NoLegend() +
  ggtitle("") +
  dittoBarPlot(
  data,
  var = "seurat_clusters",
  group.by = "patient", 
  scale = "count",
  color.panel = as.vector(pals::trubetskoy())
) +
  ggtitle("") &
  theme(text = element_text(size = 20)) &
  guides(fill=guide_legend(ncol=2))
```

# TCR

```{r eval = FALSE}
S1 <- read.csv(glue("{proj_dir}/data/CSF_01/jobs/4839/4839/outs/per_sample_outs/4839/vdj_t/filtered_contig_annotations.csv"))
S2 <- read.csv(glue("{proj_dir}/data/CSF_01/jobs/5792/5792/outs/per_sample_outs/5792/vdj_t/filtered_contig_annotations.csv"))
S3 <- read.csv(glue("{proj_dir}/data/CSF_01/jobs/4839/4839/outs/per_sample_outs/4839/vdj_b/filtered_contig_annotations.csv"))
S4 <- read.csv(glue("{proj_dir}/data/CSF_01/jobs/5792/5792/outs/per_sample_outs/5792/vdj_b/filtered_contig_annotations.csv"))

contig_list_TCR <- list(S1, S2)
contig_list_BCR <- list(S3, S4)

# TCR
combined_tcr <- combineTCR(contig_list_TCR, 
                ID = sample_list, 
                samples = c("CSF_01", "CSF_01")
                )

# rename to match sc
combined_tcr$CSF_01_4839$barcode <- str_remove_all(combined_tcr$CSF_01_4839$barcode, pattern = "-1$|-2$|-3$")
combined_tcr$CSF_01_5792$barcode <- str_remove_all(combined_tcr$CSF_01_5792$barcode, pattern = "-1$|-2$|-3$")

# BCR
combined_bcr <- combineBCR(contig_list_BCR,
                ID = sample_list,
                samples = c("CSF_01", "CSF_01")
                )

# rename to match sc
combined_bcr$CSF_01_4839$barcode <- str_remove_all(combined_bcr$CSF_01_4839$barcode, pattern = "-1$|-2$|-3$")
combined_bcr$CSF_01_5792$barcode <- str_remove_all(combined_bcr$CSF_01_5792$barcode, pattern = "-1$|-2$|-3$")

list.receptors <- c(combined_tcr, combined_bcr)

data <- combineExpression(
  list.receptors, 
  data, 
  cloneCall="aa", 
  proportion = FALSE, 
  cloneTypes=c(Single=1, Small=5, Medium=20, Large=50, Hyperexpanded=100))

# save annotated object with TCR data
saveRDS(data, glue("{out_dir}/all_cells_integrated.rds"))
```

```{r results='markup'}
data@meta.data[, c("patient", "Frequency", "cloneType", "CTaa", "annot")] %>% 
  filter(annot %in% c("T cells", "B cells")) %>% 
  unique() %>% 
  filter(!is.na(cloneType)) %>% 
  arrange(desc(Frequency)) %>% 
  DT::datatable(rownames = FALSE)
```

```{r fig.width=9}
colorblind_vector <- colorRampPalette(rev(c("#0D0887FF", "#47039FFF", 
              "#7301A8FF", "#9C179EFF", "#BD3786FF", "#D8576BFF",
              "#ED7953FF","#FA9E3BFF", "#FDC926FF", "#F0F921FF")))

slot(data, "meta.data")$cloneType <- factor(slot(data, "meta.data")$cloneType, 
                levels = c("Hyperexpanded (50 < X <= 100)", 
                           "Large (20 < X <= 50)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)", NA))

colorblind_vector <- colorblind_vector(5)
names(colorblind_vector) <- c("Hyperexpanded (50 < X <= 100)", 
                           "Large (20 < X <= 50)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)")
```

```{r fig.width=9}
DimPlot(data, group.by = "cloneType", pt.size = 1, order = TRUE) +
    scale_color_manual(values = colorblind_vector, na.value="grey") + 
  theme(plot.title = element_blank(),
        text = element_text(size = 18))
```

```{r fig.width=11}
DimPlot(data, group.by = "cloneType", pt.size = 1, order = TRUE, split.by = "patient") +
    scale_color_manual(values = colorblind_vector, na.value="grey") + 
  theme(plot.title = element_blank(),
        text = element_text(size = 18))
```

```{r fig.width=9}
"Number of clones (not cells!) per type and patient"
df <- data@meta.data[, c("patient", "cloneType", "CTaa", "annot")] %>% 
  filter(!is.na(CTaa)) %>% 
  filter(annot %in% c("T cells", "B cells"))
rownames(df) <- NULL
df <- unique(df)
table(df[, c("patient", "cloneType", "annot")]) %>% 
  as.data.frame() %>% 
  ggplot(aes(x=patient, y=Freq, fill=cloneType)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_text(aes(label=Freq), vjust=-0.5, color="black",
            position = position_dodge(0.9), size=3.5) +
  facet_grid(.~annot) +
  scale_fill_manual(values = colorblind_vector) +
  theme_classic() +
  theme(plot.title = element_blank(),
        text = element_text(size = 18))
```

# Glioblastoma signatures

```{r eval = FALSE}
glio_sig <- c("COL6A2", "ABCC3", "COL8A1", "FAM20A", "ADM", "CTHRC1", "PDPN", "IBSP", "MIR210HG", "GPX8", "MYL9", "PDLIM4",
              "CHST9-", "CSDC2-", "ENHO-", "FERMT1-", "IGFN1-", "LINC00836-", "MGAT4C-", "SHANK2-", "VIPR2-")
data <- UCell::AddModuleScore_UCell(data, features = list("GB_sig" = glio_sig), name = "")
```

```{r}
VlnPlot(data,
        features = "GB_sig",
        group.by = "seurat_clusters", 
        cols = as.vector(pals::trubetskoy())
        ) +
  NoLegend()
```

```{r}
p1 <- (FeaturePlot(
  data,
  features = "GB_sig",
  order = TRUE,
  pt.size = 1.5,
  cols = c("#ADD8E633", "darkgreen"),
))
```

```{r fig.width=10}
FeaturePlot(
  data,
  features = "GB_sig",
  order = TRUE,
  pt.size = 1.5,
  split.by = "patient",
  cols = c("#ADD8E633", "darkgreen"),
)
```

```{r fix clusters, eval = FALSE}
Idents(data) <- "normal"
data <- CellSelector(plot = p1, object = data, ident = "tumor")
data$type <- as.factor(as.character(Idents(data)))

saveRDS(data, glue("{out_dir}/all_cells_signature_type.rds"))
```

```{r}
DimPlot(data, group.by = "type", cols = c("grey", "#d6604d"), pt.size = 2)
```

```{r eval = FALSE}
Idents(data) <- "type"

markers <- FindMarkers(
  object = data,
  only.pos = TRUE,
  ident.1 = "tumor"
)
markers$gene <- rownames(markers)

# save file
saveRDS(markers, glue("{out_dir}/Glioblastoma_tumor_markers.rds"))
# write to excel file
openxlsx::write.xlsx(markers, 
                     file = glue("{out_dir}/Glioblastoma_tumor_markers.xlsx"),
                     overwrite = TRUE)
```

Top genes

```{r}
markers <- readRDS(glue("{out_dir}/Glioblastoma_tumor_markers.rds"))
m <- markers %>% 
  filter(p_val_adj < 0.01) %>% 
  arrange(desc(avg_log2FC)) %>% 
  head(n = 20) %>% 
  pull(gene)
```

```{r fig.width=12, fig.height=3}
DotPlot(data,
        features = m,
        cols = "RdYlBu",
        group.by = "patient",
        dot.scale = 24
) +
  RotatedAxis()
```

```{r results='markup'}
markers %>% 
  filter(p_val_adj < 0.01) %>% 
  arrange(desc(avg_log2FC)) %>% 
  DT::datatable(rownames = FALSE)
```


<a href="#top">Back to top</a>
