---
title: "Myeloid cells scVI integrated"
author:
- name: Paula Nieto
  affiliation: 
  - Centro Nacional de Análisis Genómico (CNAG)
  email: paula.nieto@cnag.crg.eu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  results = "hide",
  warning = FALSE,
  message = FALSE,
  tidy = TRUE
)
```

```{r surce-utils, include=FALSE}
tryCatch({
  source("/scratch/devel/pnieto/scripts/r_utils/utils.R")
}, error = function(e) {
  source("S:/scripts/r_utils/utils.R")
})
library(dittoSeq)
```

```{r set-params}
root <- get_root_dir()
proj_dir <- glue("{root}/CSF")
data_dir <- glue("{proj_dir}/output/integration/Myeloid cells")
out_dir <- data_dir
```

```{r create-output-folder}
# create output folder if it doesn't exist yet
if (!file.exists(out_dir)) {
  dir.create(out_dir)
}
```

```{r}
data <- readRDS(glue("{data_dir}/Myeloid_cells_annotated.rds"))
Idents(data) <- "leiden_res_1"
```

```{r}
# set up color palettes
pal_patients <- as.vector(pals::polychrome())
pal_projects <-as.vector(pals::alphabet())
pal_disease <-as.vector(pals::trubetskoy())
pal_clusters <- c(ggsci::pal_d3("category20")(20), ggsci::pal_d3("category20b")(20))
pal_gene_exp <- c("#ADD8E633", "#E46726")
pal_annot <- as.vector(pals::glasbey())
pal_clones <- colorRampPalette(rev(c("#0D0887FF", "#47039FFF", 
              "#7301A8FF", "#9C179EFF", "#BD3786FF", "#D8576BFF",
              "#ED7953FF","#FA9E3BFF", "#FDC926FF", "#F0F921FF")))(5)
names(pal_clones) <- c("Hyperexpanded (50 < X <= 100)", 
                           "Large (20 < X <= 50)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)")
```

# Integration and Clustering

```{r load and process data, eval = FALSE}
data <- readRDS(glue("{data_dir}/Myeloid_cells_merged.rds"))

data <- data %>%
  NormalizeData() %>% 
  FindVariableFeatures(nfeatures = 2000) %>%
  ScaleData(verbose = FALSE) %>%
  RunPCA(verbose = FALSE) %>%
  RunUMAP(dims = 1:20, verbose = FALSE) %>% 
  RunUMAP(dims = 1:20, verbose = FALSE, reduction.key = "UMAP_scVI_", reduction.name = "umap_scvi")

# fix mistaken patient
data$patient[data$library == 3885] <- "P12"
data$patient_sample <- paste(data$patient, data$sample, sep = "_")
Idents(data) <- "leiden_res_1"
```

```{r recode patient, eval = FALSE}
data$disease <- "none"
data$disease[data$patient %in% c("P01", "P06", "P10", "P11", "P15")] <- "Lymphoma"
data$disease[data$patient %in% c("P02", "P05")] <- "Glioblastoma"
data$disease[data$patient %in% c("P03", "P08", "P09", "P12", "P16")] <- "Brain met"
data$disease[data$patient %in% c("P04", "P07", "P13", "P14")] <- "Inflammatory"
```

```{r scVI metadata and UMAP coordinates, eval = FALSE}
# Read the CSV file with the clusters from scVI
clusters <- read.csv(glue("{data_dir}/Myeloid_cells_scVI_clusters.csv"))
rownames(clusters) <- clusters$X
clusters$X <- NULL
# add clusters metadata to seu obj
data <- AddMetaData(data, metadata = clusters)

umap <- read.csv(glue("{data_dir}/Myeloid_cells_scVI_UMAP.csv"))
rownames(umap) <- umap$X
umap$X <- NULL
colnames(umap) <- c("UMAPscVI_1", "UMAPscVI_2")
data@reductions$umap_scvi@cell.embeddings <- as.matrix(umap)
```

Uncorrected UMAP

```{r fig.width=10}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap", 
  group.by = "patient_sample",
  shuffle = TRUE,
  cols = pal_patients
  ) +
  DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap", 
  group.by = "project",
  shuffle = TRUE,
  cols = pal_projects
  )
```

scVI corrected UMAP

```{r fig.width=10}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "patient_sample",
  shuffle = TRUE,
  cols = pal_patients
  ) +
  DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "project",
  shuffle = TRUE,
  cols = pal_projects
  )
```

```{r}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "leiden_res_1",
  cols = pal_clusters,
  label = TRUE
  )
```

```{r fig.width=10, fig.height=10}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "leiden_res_1",
  cols = pal_clusters,
  split.by = "patient_sample",
  ncol = 4
  )
```

```{r}
FeaturePlot(
  data,
  features = c("CD3E", "CD3D", "CD68", "MS4A1"),
  order = TRUE,
  pt.size = 1,
  ncol = 2,
  label = TRUE,
  reduction = "umap_scvi", 
  cols = pal_gene_exp,
)
```

```{r}
VlnPlot(
  data,
  features = c("CD3E", "CD3D", "MS4A1", "CD79A", "CD68"),
  group.by = "leiden_res_1",
  cols = ggsci::pal_d3("category20")(20),
  pt.size = 0
)
```

# M1/M2 signatures

```{r}
source("/scratch/devel/pnieto/scripts/r_utils/marker_genes.R")
signatures <- list(
  "M1" = grep(marker_genes$`M1 Macrophages`, pattern = "-|APOE|APOC1|CD68|C1QA|C1QB|C1QC", value = TRUE, invert = TRUE),
  "M2" = grep(marker_genes$`M2 Macrophages`, pattern = "-|APOE|APOC1|CD68|C1QA|C1QB|C1QC", value = TRUE, invert = TRUE)
)
```

```{r eval = FALSE}
data <- UCell::AddModuleScore_UCell(data, features = signatures, name = "")
```

```{r}
VlnPlot(data,
        features = c("M1", "M2"),
        group.by = "leiden_res_1", 
        cols = pal_clusters,
        pt.size = 0
        ) +
  NoLegend()
```

```{r fig.width=10}
DotPlot(
  data, 
  features = unique(c(signatures$M1, signatures$M2)),
  cols = "RdYlBu"
) +
  RotatedAxis()
```

```{r}
data$leiden_res_1 <- as.factor(data$leiden_res_1)
dittoScatterPlot(
    object = data,
    x.var = "M1", 
    y.var = "M2",
    color.var = "leiden_res_1",
    color.panel = pal_clusters
    )
```

# Neutrophils signatures

```{r}
neu_sig <- readRDS(glue("{proj_dir}/data/sig_df.rds"))
neu_sig$gene <- str_to_upper(neu_sig$gene)
neu_sig <- split(neu_sig$gene,neu_sig$signature)
```

```{r eval = FALSE}
data <- UCell::AddModuleScore_UCell(data, features = neu_sig, name = "")
```

```{r}
VlnPlot(subset(data, m_annot == "Neutro"),
        features = names(neu_sig)
        )
```

```{r}
FeaturePlot(
  subset(data, m_annot == "Neutro"),
  features = names(neu_sig),
  order = TRUE,
  pt.size = 2,
  ncol = 2,
  reduction = "umap_scvi", 
  cols = pal_gene_exp,
) &
  theme(title = element_text(size = 10))
```

```{r fig.width=10}
DotPlot(
  subset(data, m_annot == "Neutro"),
  features = names(neu_sig),
  cols = "RdYlBu"
) +
  RotatedAxis()
```

***

```{r find cluster markers, eval = FALSE}
Idents(data) <- "leiden_res_1"
markers <- FindAllMarkers(
  object = data,
  only.pos = TRUE
)

# save file
saveRDS(markers, glue("{out_dir}/markers/marker_genes_res1_scVI.rds"))
# write to excel file
openxlsx::write.xlsx(split(markers, markers$cluster), 
                     file = glue("{out_dir}/markers/marker_genes_res1_scVI.xlsx"),
                     overwrite = TRUE)
```

# Annotation

Old annotation

```{r}
DimPlot(
  data, 
  group.by = "auto_annot",
  cols = as.vector(pals::polychrome()),
  pt.size = 1,
  shuffle = TRUE, 
  reduction = "umap_scvi"
)
```

```{r annotation, eval = FALSE}
data$leiden_res_1 <- as.character(data$leiden_res_1)
new.cluster.ids <- c("Mono classical", "DC non-inflamatory CD1C+", "Mac M2 TREM2+", "Mac M2 TREM2+", "pDC", "doublets", "bad", "bad", "doublets", "Mac M2 TREM2+", "DC1 CLEC9A+", "DC ITGAX+","Mono intermediate", "Mac M1", "DCs mreg LAMP3", "doublets", "doublets", "DC1 CLEC9A+", "pDC", "Neutro")
# assign annotation to m_annot
data$barcode <- rownames(data@meta.data)
df_meta <- data@meta.data[, c("barcode", "leiden_res_1")]
df_annot <- data.frame(
  "leiden_res_1" = as.character(c(0:19)),
  "m_annot" = new.cluster.ids
)
df_meta <- merge(df_meta, df_annot, all.x = TRUE)
rownames(df_meta) <- df_meta$barcode
data <- AddMetaData(data, metadata = df_meta[,c("barcode", "m_annot")])
data <- subset(data, m_annot %in% c("doublets", "bad quality", "RBC", "bad"), invert = TRUE)
data$m_annot <- as.character(data$m_annot)
```

```{r fig.width=9}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "m_annot",
  cols = pal_annot,
  label = TRUE
  )
```

```{r find cell type markers, eval = FALSE}
Idents(data) <- "m_annot"
markers <- FindAllMarkers(
  object = data,
  only.pos = TRUE
)

# save file
saveRDS(markers, glue("{out_dir}/markers/myeloid_annotation_markers.rds"))
# write to excel file
openxlsx::write.xlsx(split(markers, markers$cluster), 
                     file = glue("{out_dir}/markers/myeloid_annotation_markers.xlsx"),
                     overwrite = TRUE)
```

```{r}
data$m_annot <- as.factor(data$m_annot)
dittoScatterPlot(
    object = data,
    x.var = "M1", 
    y.var = "M2",
    color.var = "m_annot",
    color.panel = pal_annot
    )
```

```{r}
DimPlot(
  data, 
  group.by = "disease",
  reduction = "umap_scvi", 
  cols = pal_disease,
  pt.size = 1,
  shuffle = TRUE
)
```

```{r fig.width=10, fig.height=10}
DimPlot(
  data, 
  pt.size = 1,
  reduction = "umap_scvi", 
  group.by = "m_annot",
  cols = pal_annot,
  split.by = "disease",
  ncol = 2
  )
```

```{r fig.height=9}
p1 <- table(data@meta.data[, c("m_annot")]) %>% 
  as.data.frame() %>% 
  ggplot(aes(y=Freq, x=Var1)) +
  geom_bar(stat="identity") +
  theme_minimal_hgrid() +
  labs(y = "Number of cells") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank())

p2 <- table(data@meta.data[, c("m_annot", "disease")]) %>% 
  as.data.frame() %>% 
  ggplot(aes(fill=disease, y=Freq, x=m_annot)) +
  geom_bar(position="fill", stat="identity") +
  theme_minimal_hgrid() +
  labs(x = "Cluster", y = "Proportion", fill = "Disease") +
  scale_fill_manual(values = pal_disease) +
  RotatedAxis()

(p1 + p2) +
  plot_layout(heights = c(5, 10), guides="collect") &
  theme(legend.justification = "left")
```

```{r fig.width=10, fig.height=9}
t <- table(data@meta.data[, c("m_annot", "disease", "patient_sample")]) %>% 
  as.data.frame() %>%
  filter(Freq > 0) %>% 
  mutate_if(is.factor,as.character) %>% 
  arrange(disease)
t$patient_sample <-  factor(t$patient_sample,levels = t[, c("patient_sample", "disease")] %>% unique() %>% pull(patient_sample))

# bar at the top
p1 <-  ggplot(t, aes(y=-1, fill=disease, x=patient_sample)) + 
  geom_tile() + 
  scale_fill_manual(values = pal_disease) + 
  theme_void() +
  labs(fill = "Disease")

# actual barplot
p2 <- ggplot(t, aes(fill=m_annot, y=Freq, x=patient_sample)) +
  geom_bar(position="fill", stat="identity") +
  theme_classic() +
  labs(x = "patient_sample", y = "Proportion", fill = "Cell type") +
  scale_fill_manual(values = pal_annot) +
  RotatedAxis()

t2 <- table(data@meta.data[, c("patient_sample")]) %>% 
  as.data.frame()
t2$Var1 <-  factor(t2$Var1,levels = t[, c("patient_sample", "disease")] %>% unique() %>% pull(patient_sample))

p3 <- ggplot(t2, aes(y=Freq, x=Var1)) +
  geom_bar(stat="identity") +
  theme_minimal_hgrid() +
  labs(y = "Number of cells") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank())

# patchwork
(p3 + p1 + p2) +
  plot_layout(heights = c(5, 0.5, 10), guides="collect") &
  theme(legend.justification = "left")
```

```{r save obj, eval = FALSE}
saveRDS(data, glue("{data_dir}/Myeloid_cells_annotated.rds"))
```
